const YoutubeActionTypes = {
  FETCH_YOUTUBE_PLAYLISTS: "FETCH_YOUTUBE_PLAYLISTS",
  FETCH_YOUTUBE_PLAYLISTITEMS: "FETCH_YOUTUBE_PLAYLISTITEMS",
  START_YOUTUBE_VIDEO: "START_YOUTUBE_VIDEO",
  STOP_YOUTUBE_VIDEO: "STOP_YOUTUBE_VIDEO",
  SEARCH_YOUTUBE_CHANNEL: "SEARCH_YOUTUBE_CHANNEL"
};

export default YoutubeActionTypes;
